# Site settings
title: Josh Duffneys Blog
description: 'Senior Systems Engineer focused on DevOps within a Windows World'
url: "https://duffney.github.io"
enforce_ssl: duffney.github.io
baseurl: /
google_analytics: 'UA-41356215-2'

author:
  name: 'Josh Duffney'
  email: duffney@outlook.com
  twitter_username: joshduffney
  github_username:  duffney
  linkedin_username:  joshduffney

pages_list:
  About: '/about/'
  Archives: '/archives/'
  

# Build settings
destination: _site
paginate: 10
permalink: /:title
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-gist

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
